language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - "pip install -r requirements-nodbus.txt --use-mirrors"
  - pip install coveralls --use-mirrors
script:
  - coverage run --source=cbus setup.py -q nosetests
after_success:
  - coveralls