language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "pypy"
install:
  - "pip install -r requirements-nodbus.txt"
  - pip install coveralls
script:
  - coverage run --source=cbus setup.py test
after_success:
  - coveralls