language: python
python:
  - "3.7"

install:
  - "pip install -r requirements.txt -r requirements-tests.txt"
  - pip install coveralls

after_success:
  - coveralls

jobs:
  include:
    - script: coverage run setup.py test
    - script: pytype
