language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - "pip install -r requirements-nodbus.txt --use-mirrors"
  - pip install coveralls --use-mirrors
script:
  - nosetests --with-coverage --cover-package cbus
after_success:
  - coveralls